name: '自動部署至GCE'

# 觸發條件
on:
  push:
    branches:
      - 'feature/2.0'

# 執行工作
jobs:
  # 打包和部署
  build-and-deploy:
    # 作業系統
    runs-on: 'ubuntu-latest'

    # 步驟
    steps:
      # 下載原始碼
      - name: '下載原始碼'
        uses: 'actions/checkout@v4'

      # 設定Node.js環境
      - name: '設定Node.js環境'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '24'
          cache: 'npm'

      # 打包專案
      - name: '打包專案'
        run: |
          npm install
          npm run build

      # 驗證GCP權限
      - name: '驗證GCP權限'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      # 設定Gcloud CLI
      - name: '設定Gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'

      # 部署到GCE
      - name: '部署到GCE'
        run: |
          export RSYNC_RSH="gcloud compute ssh --zone=${{ secrets.GCE_ZONE }} --quiet"

          rsync -avz --delete \
            ./dist/ \
            ${{ secrets.GCE_NAME }}:${{ secrets.GCE_PATH }}/dev-shop-v2.coord.tw/dist \
            --rsync-path="sudo rsync"
